version: '3'

services:
  smtp-artha:
    build:
      context: .
      dockerfile: dockerfile
    container_name: smtp-artha
    image: smtp-artha
    ports:
      - 3030:3030
    env_file:
      - proudction.env
    networks:
      - smtp_artha_network
    

networks:
  smtp_artha_network: 
    name: smtp_artha_network
